### ISSUE TITLE
Asteroid Variety

### ISSUE THREAD

**Issue by JWR26** [JWR26/ArcadeSpaceFighter#1]
Currently an asteroid has set shape and mass and will always be directed towards the middle of the screen. To allow for greater variety the following criteria should be met for asteroids:

- [x] Random shape when added to the scene tree
- [x] Random direction accross the screen
- [x] Speed inversly proportional size (small move fast, big move slow)
- [x] Mass proportional to size (small are light, big are heavy)

**Comment by JWR26** [comment]
updated following #5

**Comment by dslh** [comment]
> Speed inversly proportional size (small move fast, big move slow)

It looks like this requirement is already covered by our use of `apply_central_impulse` to set asteroid velocity. The documentation isn't explicit about it, but you might expect an impulse to take mass into account, and spelunking in the Godot source code confirms it:

https://github.com/godotengine/godot/blob/c3539b4561f9b4d7dc4ba1c5859217e7fbf9c6fe/servers/physics_2d/godot_body_2d.h#L227-L229

The effect is somewhat lost because of the large range between `MIN_SPEED` and `MAX_SPEED` in `asteroid.gd`. Smaller asteroids will tend to be faster than larger ones, but not always. Maybe we should narrow down the speed range, or make it a fixed value? What do you think?

**Comment by JWR26** [comment]
This appears done for now! Great work! 👍

**Comment by JWR26** [comment]
This appears done for now! Great work! 👍
